detectors:
  Attribute:
    enabled: false
    exclude: []
  BooleanParameter:
    enabled: true
    exclude: ["UserSessionConsumeCredit#initialize"]
  ClassVariable:
    enabled: false
    exclude: []
  ControlParameter:
    enabled: false
    exclude: []
  DataClump:
    enabled: true
    exclude: ["SlackService"]
    max_copies: 2
    min_clump_size: 2
  DuplicateMethodCall:
    enabled: true
    exclude:
      [
        "UserSessions::RemindersJob#perform",
        "EmployeeSessionsQuery#sorted_future_sessions",
        "Subscription#assign_stripe_attrs",
        "Users::CreditsExpirationJob#perform",
        "Api::V1::StripeController#webhook",
        "SonarService#add_update_customer",
        "AddAttachment#call",
        "ActiveCampaignService#custom_deal_fields",
        "User#update_external_records",
        "UserSessionConsumeCredit#save!",
        "Users::InactiveMembersJob#perform",
      ]
    max_calls: 1
    allow_calls: ["render :new"]
  FeatureEnvy:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  IrresponsibleModule:
    enabled: false
    exclude: []
  LongParameterList:
    enabled: true
    exclude: [StripeService#self.upcoming_invoice, StripeService#self.update_subscription]
    max_params: 4
    overrides:
      initialize:
        max_params: 5
  LongYieldList:
    enabled: true
    exclude: []
    max_params: 3
  ManualDispatch:
    enabled: true
    exclude: []
  MissingSafeMethod:
    enabled: false
    exclude: []
  ModuleInitialize:
    enabled: true
    exclude: []
  NestedIterators:
    enabled: true
    exclude: ["Sessions::TimeoutWaitlistsJob#perform"]
    max_allowed_nesting: 2
    ignore_iterators: []
  NilCheck:
    enabled: false
    exclude: []
  RepeatedConditional:
    enabled: true
    exclude: ["Api::V1::SubscriptionsController"]
    max_ifs: 3
  SubclassedFromCoreClass:
    enabled: true
    exclude: []
  TooManyConstants:
    enabled: false
    exclude: ["Event"]
    max_constants: 5
  TooManyInstanceVariables:
    enabled: true
    exclude: []
    max_instance_variables: 9
  TooManyMethods:
    enabled: true
    exclude: []
    max_methods: 25
  TooManyStatements:
    enabled: false
  UncommunicativeMethodName:
    enabled: true
    exclude: []
    reject:
      - "/^[a-z]$/"
      - "/[0-9]$/"
      - "/[A-Z]/"
    accept: []
  UncommunicativeModuleName:
    enabled: true
    exclude: []
    reject:
      - "/^.$/"
      - "/[0-9]$/"
    accept:
      - Inline::C
      - "/V[0-9]/"
  UncommunicativeParameterName:
    enabled: true
    exclude: []
    reject:
      - "/^.$/"
      - "/[0-9]$/"
      - "/[A-Z]/"
    accept: []
  UncommunicativeVariableName:
    enabled: true
    exclude: ["EmployeeSessionsQuery#sorted_future_sessions", "User#update_external_records"]
    reject:
      - "/^.$/"
      - "/[0-9]$/"
      - "/[A-Z]/"
    accept:
      - _
      - e
  UnusedParameters:
    enabled: true
    exclude: []
  UnusedPrivateMethod:
    enabled: false
  UtilityFunction:
    enabled: false

exclude_paths:
  - config
