detectors:
  Attribute:
    enabled: false
    exclude: []
  BooleanParameter:
    enabled: true
    exclude: []
  ClassVariable:
    enabled: false
    exclude: []
  ControlParameter:
    enabled: true
    exclude: ['KlaviyoService#specific_event_attributes']
  DataClump:
    enabled: true
    exclude: []
    max_copies: 2
    min_clump_size: 2
  DuplicateMethodCall:
    enabled: true
    exclude: ['SessionRemindersJob#perform', 'SonarService#message_received', 'EmployeeSessionsQuery#sorted_future_sessions']
    max_calls: 1
    allow_calls: []
  FeatureEnvy:
    enabled: true
    exclude: [
      'CreatePurchase#call',
      'KlaviyoService#purchase_placed',
      'KlaviyoService#general_event_attributes',
      'EmployeeSessionsQuery#sorted_future_sessions'  
    ]
  InstanceVariableAssumption:
    enabled: false
  IrresponsibleModule:
    enabled: false
    exclude: []
  LongParameterList:
    enabled: true
    exclude: []
    max_params: 4
    overrides:
      initialize:
        max_params: 5
  LongYieldList:
    enabled: true
    exclude: []
    max_params: 3
  ManualDispatch:
    enabled: true
    exclude: []
  MissingSafeMethod:
    enabled: false
    exclude: []
  ModuleInitialize:
    enabled: true
    exclude: []
  NestedIterators:
    enabled: true
    exclude: []
    max_allowed_nesting: 2
    ignore_iterators: []
  NilCheck:
    enabled: false
    exclude: []
  RepeatedConditional:
    enabled: true
    exclude: []
    max_ifs: 3
  SubclassedFromCoreClass:
    enabled: true
    exclude: []
  TooManyConstants:
    enabled: true
    exclude: ['Event']
    max_constants: 5
  TooManyInstanceVariables:
    enabled: true
    exclude: []
    max_instance_variables: 9
  TooManyMethods:
    enabled: true
    exclude: []
    max_methods: 25
  TooManyStatements:
    enabled: true
    exclude: ['SessionRemindersJob#perform']
    max_statements: 12
  UncommunicativeMethodName:
    enabled: true
    exclude: []
    reject:
      - "/^[a-z]$/"
      - "/[0-9]$/"
      - "/[A-Z]/"
    accept: []
  UncommunicativeModuleName:
    enabled: true
    exclude: []
    reject:
      - "/^.$/"
      - "/[0-9]$/"
    accept:
      - Inline::C
      - "/V[0-9]/"
  UncommunicativeParameterName:
    enabled: true
    exclude: []
    reject:
      - "/^.$/"
      - "/[0-9]$/"
      - "/[A-Z]/"
    accept: []
  UncommunicativeVariableName:
    enabled: true
    exclude: [
      'StripeController#load_event',
      'SlackService#session_booked',
      'SonarService#add_customer',
      'SonarService#send_message',
      'EmployeeSessionsQuery#sorted_future_sessions'
    ]
    reject:
      - "/^.$/"
      - "/[0-9]$/"
      - "/[A-Z]/"
    accept:
      - _
  UnusedParameters:
    enabled: true
    exclude: []
  UnusedPrivateMethod:
    enabled: false
  UtilityFunction:
    enabled: false

exclude_paths:
  - config
