require: rubocop-rails

AllCops:
  Exclude:
    - db/schema.rb

Style/Documentation:
  Enabled: false

Layout/ClassStructure:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Exclude:
    - app/views/api/**/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  CountComments: false # count full line comments?
  Max: 25
  Exclude:
    - config/**/*
    - spec/**/*
    - app/admin/**/*
    - app/models/concerns/employee_session.rb

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  CountComments: false # count full line comments?
  Max: 200

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Max: 6
  Exclude:
    - app/jobs/user_session_reminders_job.rb
    - app/jobs/sem_session_reminders_job.rb
    - app/jobs/referee_session_reminders_job.rb
    - app/decorators/employee_session_confirmed.rb

Metrics/MethodLength:
  CountComments: false # count full line comments?
  Max: 24
  Exclude:
    - app/jobs/user_session_reminders_job.rb
    - app/jobs/sem_session_reminders_job.rb
    - app/jobs/referee_session_reminders_job.rb
    - app/services/klaviyo_service.rb

Metrics/ModuleLength:
  CountComments: false # count full line comments?
  Max: 200

Metrics/LineLength:
  Max: 200
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowURI: true
  Exclude:
    - db/migrate/20161011184702_devise_create_admin_users.rb
    - db/migrate/20161011151353_devise_create_users.rb
    - db/migrate/20161027190856_create_delayed_jobs.rb
    - db/migrate/20181102142200_create_active_storage_tables.active_storage.rb
    - app/services/klaviyo_service.rb
  URISchemes:
    - http
    - https

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 12

Rails:
  Enabled: true

Rails/Delegate:
  Enabled: true
  Exclude:
    - app/controllers/api/concerns/act_as_api_request.rb

Rails/FilePath:
  Enabled: false

Rails/SaveBang:
  Enabled: true
  Exclude:
    - app/services/stripe_service.rb
    - app/services/twilio_service.rb

Rails/SkipsModelValidations:
  Exclude:
    - app/controllers/api/v1/sem/user_sessions_controller.rb

Rails/HasManyOrHasOneDependent:
  Exclude:
    - app/models/location.rb

Rails/NotNullColumn:
  Exclude:
    - db/migrate/20200508180924_add_expiration_date_to_promo_codes.rb

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ExpandPathArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/ReturnNil:
  Enabled: true

Style/GuardClause:
  Exclude:
    - app/controllers/api/v1/confirmations_controller.rb

Metrics/AbcSize:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: true
  Exclude:
    - app/jobs/email_to_inactive_users_job.rb
