require: rubocop-rails

AllCops:
  Exclude:
    - db/schema.rb

Style/Documentation:
  Enabled: false

Layout/ClassStructure:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Exclude:
    - app/views/api/**/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/HandleExceptions:
  Exclude:
    - app/jobs/user_sessions/charge_not_show_up_job.rb

Metrics/BlockLength:
  CountComments: false # count full line comments?
  Max: 25
  Exclude:
    - config/**/*
    - spec/**/*
    - app/admin/**/*
    - app/models/concerns/employee_session.rb
    - app/interactors/users/charge.rb

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  CountComments: false # count full line comments?
  Max: 200
  Exclude:
    - app/services/active_campaign_service.rb
    - app/services/stripe_service.rb

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Max: 8
  Exclude:
    - app/jobs/user_sessions/reminders_job.rb
    - app/jobs/users/inactive_non_members_job.rb
    - app/decorators/employee_session_confirmed.rb
    - app/controllers/api/v1/stripe_controller.rb
    - app/services/active_campaign_service.rb
    - app/interactors/user_sessions/create.rb
    - app/models/promo_code.rb
    - app/interactors/users/charge.rb
    - app/interactors/subscriptions/update_user_subscription_credits.rb
    - app/decorators/session_decorator.rb

Metrics/MethodLength:
  CountComments: false # count full line comments?
  Max: 30
  Exclude:
    - app/jobs/user_session_reminders_job.rb
    - app/services/active_campaign_service.rb
    - app/controllers/api/v1/stripe_controller.rb
    - app/decorators/canceled_user_session.rb
    - app/jobs/users/credits_expiration_job.rb
    - app/interactors/user_sessions/create.rb
    - spec/support/mocks/stripe_mocker.rb
    - app/interactors/users/charge.rb
    - app/jobs/users/inactive_non_members_job.rb
    - app/interactors/subscriptions/create_subscription.rb

Metrics/ModuleLength:
  CountComments: false # count full line comments?
  Max: 200

Metrics/LineLength:
  Max: 100
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowURI: true
  Exclude:
    - db/migrate/20161011184702_devise_create_admin_users.rb
    - db/migrate/20161011151353_devise_create_users.rb
    - db/migrate/20161027190856_create_delayed_jobs.rb
    - db/migrate/20181102142200_create_active_storage_tables.active_storage.rb
  URISchemes:
    - http
    - https

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true
  Exclude:
    - spec/support/mocks/stripe_mocker.rb
    - app/interactors/users/charge.rb

Metrics/PerceivedComplexity:
  Max: 20

Rails:
  Enabled: true

Rails/Delegate:
  Enabled: true
  Exclude:
    - app/controllers/api/concerns/act_as_api_request.rb

Rails/FilePath:
  Enabled: false

Rails/SaveBang:
  Enabled: true
  Exclude:
    - app/services/stripe_service.rb
    - app/services/twilio_service.rb

Rails/SkipsModelValidations:
  Exclude:
    - app/interactors/promo_codes/create_user_promo_code.rb
    - app/interactors/promo_codes/increment_times_used.rb
    - app/models/user.rb
    - app/jobs/sessions/timeout_waitlists_job.rb
    - spec/models/product_spec.rb

Rails/HasManyOrHasOneDependent:
  Exclude:
    - app/models/location.rb
    - app/models/skill_level.rb
    - app/models/session.rb
    - app/models/product.rb

Rails/NotNullColumn:
  Exclude:
    - db/migrate/20200508180924_add_expiration_date_to_promo_codes.rb

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ExpandPathArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/ReturnNil:
  Enabled: true

Style/GuardClause:
  Exclude:
    - app/controllers/api/v1/confirmations_controller.rb
    - app/interactors/promo_codes/create_user_promo_code.rb
    - app/models/promo_code.rb

Style/IfUnlessModifier:
  Exclude:
    - app/models/promo_code.rb

Style/EmptyCaseCondition:
  Exclude:
    - app/services/sonar_service.rb

Metrics/AbcSize:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - spec/**/*
    - config/routes.rb
