FORMAT: 1A
HOST: https://cross-court-testing.herokuapp.com

# API BASE

Rails Api Base is a boilerplate project for JSON RESTful APIs. It follows the community best practices in terms of standards, security and maintainability, integrating a variety of testing and code quality tools.

## Users Collection [/api/v1/users]

### Sign Up [POST]

+ Request (application/json)
    + Attributes
      + user (Profile Edition, required)


+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com


    + Attributes
      + user (Profile Response, required)

+ Response 401


## Current user's profile [/api/v1/user/profile]

### Get current user profile [GET]

+ Request (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            uid: test@test.com


+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com


    + Attributes
      + user (Profile Response, required)


+ Response 401


### Update current user profile [PUT]

+ Request (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            uid: test@test.com

    + Attributes
      + user (Profile Edition, required)

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com


    + Attributes
      + user (Profile Response, required)

## Get current user info [/api/v1/user]

### Get user [GET]

+ Request (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            uid: test@test.com



+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com


    + Attributes
      + user (User, required)

+ Response 401


## Login [/api/v1/users/sign_in]

### Login [POST]

+ Request (application/json)

    + Body

            {
              "user":
                {
                  "email": "test@gmail.com",
                  "password": "password"
                }
            }


+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com


    + Attributes
      + user (Profile Response, required)

+ Response 401

## Logout [/api/v1/users/sign_out]

### Logout [DELETE]

+ Request (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

+ Response 200 (application/json)


## Reset password [/api/v1/users/password]

More information of how reset password works: https://github.com/lynndylanhurley/devise_token_auth/wiki/Reset-Password-Flow

### Reset password [POST]

Use this route to send a password reset confirmation email

+ Request (application/json)
    + Body

            {
              "email": "test@test.com",
              "redirect_url": "http://www.example.com"
            }

+ Response 200 (application/json)
    + Body

            {
              "success": true,
              "message": "An email has been sent to 'example@mail.com' containing instructions for resetting your password."
            }

### Reset password [PUT]

Use this route to change user's passwords

+ Request (application/json)
    + Parameters
        + reset_password_token (string, required)

    + Body

            {
              "password": "12345678",
              "password_confirmation": "12345678"
            }

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

    + Attributes (Profile Response)

## Edit reset password [/api/v1/users/password/edit]

### Edit reset password [GET]

This route is the destination URL for password reset confirmation

+ Request (application/json)
    + Parameters
        + reset_password_token (string, required)
        + redirect_url (string)

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

## Locations [/api/v1/locations]

### Get locations [GET]

+ Request (application/json)

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

    + Attributes (Locations array)

## Sessions [/api/v1/sessions{?from_date,location_id}]

### Get sessions [GET]

+ Parameters
    + location_id
    + from_date

+ Request (application/json)

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

    + Attributes (array[Session short])

### Get session [GET /api/v1/sessions/{id}{?date}]

+ Request (application/json)
    + Parameters
        + id (number, required)
        + date (string, required)

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

    + Attributes (Session)

## New User session [/api/v1/sessions/{session_id}/user_sessions]

### Reserve session [POST]

+ Request (application/json)
    + Parameters
        + session_id (number, required)

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

    + Attributes (Session Request)

## User sessions [/api/v1/user_sessions]

### Get user_sessions [GET]

+ Request (application/json)

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

    + Attributes (UserSessions response)


### Cancel user_session [PUT /api/v1/user_sessions/{id}/cancel]

+ Request (application/json)
    + Parameters
        + id (required, number)

+ Response 204 (application/json)


### Confirm user_session [PUT /api/v1/user_sessions/{id}/confirm]

+ Request (application/json)
    + Parameters
        + id (required, number)

+ Response 204 (application/json)

## Sem [/api/v1/sem]

### Check in user sessions [PUT /api/v1/sem/user_sessions/check_in]

+ Request (application/json)
    + Parameters
        + ids (required, array[number])

+ Response 204 (application/json)


### Get session info [GET /api/v1/sem/sessions/{id}]

+ Request (application/json)
    + Parameters
        + id (required, number)
        + date (required, string)

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

    + Attributes (Sem session response)

## Purchases [/api/v1/purchases]

### Get purchases [GET]

+ Request (application/json)

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

    + Attributes (array[Purchase])


### Create purchase [POST]

+ Request (application/json)
    
    + Body

            {
                "payment_method": "pm_123456789",
                "product_id": 1
            }

+ Response 204 (application/json)


## Free session [/api/v1/purchases/claim_free_session]

### Claim free session [PUT]

+ Request (application/json)

+ Response 204 (application/json)


## Products [/api/v1/products]

### Get products [GET]

+ Request (application/json)

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

    + Attributes (array[Product])


## Payment methods [/api/v1/payment_methods]

### Get payment methods [GET]

+ Request (application/json)

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

    + Attributes (array[Payment method])

### Create payment method [POST]

+ Request (application/json)

    + Body

            {
              "payment_method": "pm_123456789"
            }

+ Response 204 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com


### Destroy payment method [DELETE /api/v1/payment_method/{id}]

+ Request (application/json)
    + Parameters
        + id (string, required)

+ Response 204 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com


### Legals [GET /api/v1/legals/{title}]

+ Request (application/json)
    + Parameters
        + title (string, required)

+ Response 204 (application/json)
    + Attributes (Legal)


# Data Structures

## Profile Response (object)
+ id: 100 (number)
+ email: test@test.com (string)
+ provider: email, facebook, twitter (enum[string]) - it's way the user logins
+ uid: test@test.com (string) - the provider identifier
+ name: jdoe (string)
+ phone_number: 1233456 (string)
+ created_at: 2017-02-23T13:54:33.283Z (string)

## Profile Edition (object)
+ name: John Doe (string)
+ phone_number: 1233456 (string)

## User (object)
+ email: test@test.com (string)
+ name: John Doe (string)
+ phone_number: 1233456 (string)

## Session Request (object)
+ date: '20/12/2019' (string)

## Session (object)
+ id (number)
+ start_time: 2019-11-14T14:59:11Z (string)
+ time: 2000-01-01T16:00:00Z (string)
+ location (Location)
+ user_session (Short user session)
+ full (boolean)
+ sem (Employee)
+ referee (Employee)

## Session short (object)
+ id (number)
+ start_time: 2019-11-14T14:59:11Z (string)
+ time: 2000-01-01T16:00:00Z (string)
+ location (Location short)

## Location (object)
+ id (number)
+ name (string)
+ direction (string)
+ lat (number)
+ lng (number)
+ city (string)
+ zipcode (string)
+ image_url (string)

## Location short (object)
+ name (string)

## Locations array (object)
+ locations (array[Location])

## Purchase (object)
+ id (number)
+ price (number)
+ date (string)

## UserSession (object)
+ id (number)
+ date (string)
+ state (string)
+ session (Session)
+ in_cancellation_time (boolean)
+ in_confirmation_time (boolean)

## UserSessions response (object)
+ previous_sessions (array[UserSession])
+ upcoming_sessions (array[UserSession])
+ sem_upcoming_sessions (array[SemSession])

## SemSession (object)
+ id (number)
+ date (string)
+ session (Session)
+ in_start_time (boolean)

## Product (object)
+ price (number)
+ name (string)
+ description (string)
+ stripe_id (string)

## Employee (object)
+ name (string)
+ image_url (string)

## Payment method (object)
+ id: pm_123456789 (string)
+ card (Card)

## Card (object)
+ last4: 1234 (string)
+ exp_month: 08 (string)
+ exp_year: 2020 (string)
+ brand: Visa (string)

## Sem session response (object)
+ session (Session short)
+ users (array[Short sem user session])

## Short sem user session (object)
+ id (number)
+ name (string)

## Short user session (object)
+ id (number)
+ state (string)
+ in_cancellation_time (boolean)
+ in_confirmation_time (boolean)
+ date (string)

## Legal
+ text (string)
