FORMAT: 1A
HOST: http://rails5-api-base.herokuapp.com

# API BASE

Rails Api Base is a boilerplate project for JSON RESTful APIs. It follows the community best practices in terms of standards, security and maintainability, integrating a variety of testing and code quality tools.

## Users Collection [/api/v1/users]

### Sign Up [POST]

+ Request (application/json)
    + Attributes
      + user (Profile Edition, required)


+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com


    + Attributes
      + user (Profile Response, required)

+ Response 401


## Current user's profile [/api/v1/user/profile]

### Get current user profile [GET]

+ Request (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            uid: test@test.com


+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com


    + Attributes
      + user (Profile Response, required)


+ Response 401


### Update current user profile [PUT]

+ Request (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            uid: test@test.com

    + Attributes
      + user (Profile Edition, required)

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com


    + Attributes
      + user (Profile Response, required)

## Get current user info [/api/v1/user]

### Get user [GET]

+ Request (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            uid: test@test.com



+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com


    + Attributes
      + user (User, required)

+ Response 401


## Login [/api/v1/users/sign_in]

### Login [POST]

+ Request (application/json)

    + Body

            {
              "user":
                {
                  "email": "test@gmail.com",
                  "password": "password"
                }
            }


+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com


    + Attributes
      + user (Profile Response, required)

+ Response 401

## Logout [/api/v1/users/sign_out]

### Logout [DELETE]

+ Request (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

+ Response 200 (application/json)


## Reset password [/api/v1/users/password]

More information of how reset password works: https://github.com/lynndylanhurley/devise_token_auth/wiki/Reset-Password-Flow

### Reset password [POST]

Use this route to send a password reset confirmation email

+ Request (application/json)
    + Body

            {
              "email": "test@test.com",
              "redirect_url": "http://www.example.com"
            }

+ Response 200 (application/json)
    + Body

            {
              "success": true,
              "message": "An email has been sent to 'example@mail.com' containing instructions for resetting your password."
            }

### Reset password [PUT]

Use this route to change user's passwords

+ Request (application/json)
    + Parameters
        + reset_password_token (string, required)

    + Body

            {
              "password": "12345678",
              "password_confirmation": "12345678"
            }

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

    + Attributes (Profile Response)

## Edit reset password [/api/v1/users/password/edit]

### Edit reset password [GET]

This route is the destination URL for password reset confirmation

+ Request (application/json)
    + Parameters
        + reset_password_token (string, required)
        + redirect_url (string)

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

## Locations [/api/v1/locations]

### Get locations [GET]

+ Request (application/json)

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

    + Attributes (Locations array)

## Sessions [/api/v1/locations/{location_id}/sessions]

### Get sessions [GET]

+ Request (application/json)
    + Parameters
        + location_id (number, required)

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

    + Attributes (Session Response)

## User sessions [/api/v1/sessions/{session_id}/user_sessions]

### Reserve session [POST]

+ Request (application/json)
    + Parameters
        + session_id (number, required)

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client: QADgNCWRJj0LyRruqzYbBg
            expiry: 1489009792
            uid: test@test.com

    + Attributes (Session Request)

# Data Structures

## Profile Response (object)
+ id: 100 (number)
+ email: test@test.com (string)
+ provider: email, facebook, twitter (enum[string]) - it's way the user logins
+ uid: test@test.com (string) - the provider identifier
+ name: jdoe (string)
+ phone_number: 1233456 (string)
+ created_at: 2017-02-23T13:54:33.283Z (string)

## Profile Edition (object)
+ email: test@test.com (string)
+ password: 12345678 (string)
+ name: John Doe (string)
+ phone_number: 1233456 (string)

## User (object)
+ email: test@test.com (string)
+ name: John Doe (string)
+ phone_number: 1233456 (string)

## Session Request (object)
+ date: '20/12/2019' (string)

## Session Response (object)
+ id (number)
+ name (string)
+ start_time: 2019-11-14T14:59:11Z (string)
+ time: 2000-01-01T16:00:00Z (string)

## Location (object)
+ id (number)
+ name (string)
+ direction (string)
+ lat (number)
+ lng (number)

## Locations array (object)
+ locations (array[Location])
