SECRET_KEY_BASE:
SERVER_URL: "localhost:3000"
PASSWORD_RESET_URL: "http://127.0.0.1:3000"
SENDGRID_USERNAME:
SENDGRID_PASSWORD:
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
S3_BUCKET_NAME:
AWS_BUCKET_REGION:
SLACK_WEBHOOK_URL:
SLACK_CHANNEL_BOOKING:
SLACK_CHANNEL_CHURN:
SLACK_CHANNEL_PRODUCTS:
SLACK_CHANNEL_SUBSCRIPTIONS:
SLACK_CHANNEL_CHARGE_ERROR:
CANCELLATION_PERIOD:
CANCELED_OUT_OF_TIME_PRICE: "10"
FREE_SESSION_CANCELED_OUT_OF_TIME_PRICE: "10"
NO_SHOW_UP_FEE: "20"
JERSEY_RENTAL_PRICE:
TOWEL_RENTAL_PRICE:
ACTIVE_CAMPAING_API_URL:
ACTIVE_CAMPAING_API_KEY:
REFERRAL_CODE_PERCENTAGE_DISCOUNT: "50"
SONAR_ENV: sandbox
SONAR_TOKEN:
SONAR_PUBLISHABLE_KEY:
ROLLBAR_ACCESS_TOKEN:
WAITLIST_MINUTES_TOLERANCE:
CC_TEAM_EMAIL:
CC_MKTG_EMAIL:
RESERVE_TEAM_RESERVATIONS_LIMIT: "13"
NUMBER_OF_SESSIONS_TO_NOTIFY:
SKILL_RATINGS_FOR_REVIEW:
MAX_REDEMPTIONS_BY_GUEST: "1"
PAID_SUBSCRIPTION_PAUSE_PRICE: "15"
MAX_CC_CASH_SUBSCRIPTION_DISCOUNT:
FIRST_MONTH_SURVEY_LINK:
BACK_TO_BACK_TOLERANCE_MINUTES: "10"
BACK_TO_BACK_RESERVATION_WINDOW_MINUTES: "120"
