AddModelVirtualAttributeCheck: {}
AlwaysAddDbIndexCheck: {}
#CheckSaveReturnValueCheck: { }
DefaultScopeIsEvilCheck: {}
DryBundlerInCapistranoCheck: {}
#HashSyntaxCheck: { }
IsolateSeedDataCheck: {}
KeepFindersOnTheirOwnModelCheck: {}
LawOfDemeterCheck: { ignored_files: ["db/migrate", "app/jobs/inactive_users_job.rb"] }
#LongLineCheck: { max_line_length: 80 }
MoveCodeIntoControllerCheck: {}
MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck: { use_count: 2 }
MoveFinderToNamedScopeCheck: {}
MoveModelLogicIntoModelCheck:
  {
    use_count: 4,
    ignored_files:
      [
        "app/controllers/api/v1/sessions/user_sessions_controller.rb",
        "app/controllers/api/v1/confirmations_controller.rb",
      ],
  }
NeedlessDeepNestingCheck: { nested_count: 2 }
NotRescueExceptionCheck: {}
NotUseDefaultRouteCheck: {}
NotUseTimeAgoInWordsCheck: {}
OveruseRouteCustomizationsCheck: { customize_count: 10 }
ProtectMassAssignmentCheck: {}
RemoveEmptyHelpersCheck: {}
#RemoveTabCheck: { }
RemoveTrailingWhitespaceCheck: {}
# RemoveUnusedMethodsInControllersCheck: { except_methods: []}
RemoveUnusedMethodsInHelpersCheck: { except_methods: [] }
# RemoveUnusedMethodsInModelsCheck: { ignored_files: ['.*typeable\.rb'], except_methods: [] }
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
ReplaceInstanceVariableWithLocalVariableCheck: {}
RestrictAutoGeneratedRoutesCheck: {}
SimplifyRenderInControllersCheck: {}
SimplifyRenderInViewsCheck: {}
#UseBeforeFilterCheck: { customize_count: 2 }
UseModelAssociationCheck: {}
# UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
#UseParenthesesInMethodDefCheck: { }
UseObserverCheck: {}
UseQueryAttributeCheck: {}
UseSayWithTimeInMigrationsCheck: {}
UseScopeAccessCheck: {}
UseTurboSprocketsRails3Check: {}
