user_session_reminders:
  cron: "0 * * * *" # Every hour at minute 0
  class: "UserSessions::RemindersJob"
  queue: default

charge_no_show_up_players:
  cron: "0 12 * * *" # 5 AM LA
  class: "UserSessions::ChargeNotShowUpJob"
  queue: default

guests_no_show_up:
  cron: "0 13 * * *" # 6 AM LA
  class: "SessionGuests::NoShowUpJob"
  queue: default

confirm_unconfirmed_sessions:
  cron: "10 * * * *" # Every hour at minute 10
  class: "UserSessions::ConfirmUnconfirmedJob"
  queue: default

credits:
  cron: "0 11 * * *" # 4 AM LA
  class: "Users::CreditsExpirationJob"
  queue: default

send_survey_sms_to_players:
  cron: "0 * * * *" # Every hour at minute 0
  class: "Sonar::SurveySmsJob"
  queue: default

notify_inactive_players:
  cron: "0 16 * * *" # 9 AM LA
  class: "Users::InactiveNonMembersJob"
  queue: default

send_members_reminders:
  cron: "0 21 * * *" # 2 PM LA
  class: "Users::InactiveMembersJob"
  queue: default

canceled_subscriptions_reminders:
  cron: "0 17 * * *" # 10 AM LA
  class: "Subscriptions::CanceledRemindersJob"
  queue: default

timeout_waitlists_sessions:
  cron: "*/15 * * * *" # At every 15th minute
  class: "Sessions::TimeoutWaitlistsJob"
  queue: default

reserve_team:
  cron: "0 * * * *" # Every hour at minute 0
  class: "UserSessions::ReserveTeamJob"
  queue: default

cancel_subscriptions_at_period_end:
  cron: "0 15 * * *" # 8 AM LA
  class: "Subscriptions::CancelAtPeriodEndJob"
  queue: default

assign_default_session_employees:
  cron: "0 8 * * 1" # 8 AM UTC on Monday
  class: "Sessions::AssignDefaultEmployeesJob"
  queue: default

send_no_charge_session:
  cron: "10 * * * *" # Every hour at minute 10
  class: "Sessions::SendNoChargeSessionJob"
  queue: default
