user_session_reminders:
  cron: "0 * * * *"
  class: "UserSessionRemindersJob"
  queue: default

charge_no_show_up_players:
  cron: "0 2 * * *"
  class: "ChargeNotShowUpPlayersJob"
  queue: default

confirm_unconfirmed_sessions:
  cron: "10 * * * *"
  class: "ConfirmUnconfirmedSessionsJob"
  queue: default

credits:
  cron: "0 5 * * *"
  class: "CreditsJob"
  queue: default

send_survey_sms_to_players:
  cron: "0 * * * *"
  class: "Sonar::SurveySmsJob"
  queue: default

notify_inactive_players:
  cron: "0 7 * * *"
  class: "InactiveUsersJob"
  queue: default
