user_session_reminders:
  cron: "0 * * * *"
  class: "UserSessionRemindersJob"
  queue: default

referee_session_reminders:
  cron: "0 * * * *"
  class: "RefereeSessionRemindersJob"
  queue: default

sem_session_reminders:
  cron: "0 * * * *"
  class: "SemSessionRemindersJob"
  queue: default

charge_free_session_players:
  cron: "* 0 * * *"
  class: "ChargeFreeSessionPlayersJob"
  queue: default

confirm_unconfirmed_sessions:
  cron: "10 * * * *"
  class: "ConfirmUnconfirmedSessionsJob"
  queue: default

free_credits:
  cron: "0 5 * * *"
  class: "FreeCreditsJob"
  queue: default

send_survey_sms_to_players:
  cron: "0 * * * *"
  class: "SurveySmsJob"
  queue: default
