session_reminders:
  cron: "0 * * * *"
  class: "SessionRemindersJob"
  queue: default

charge_free_session_players:
  cron: "* 0 * * *"
  class: "ChargeFreeSessionPlayersJob"
  queue: default

confirm_unconfirmed_sessions:
  cron: "10 * * * *"
  class: "ConfirmUnconfirmedSessionsJob"
  queue: default

remove_expired_free_credits:
  cron: "0 5 * * *"
  class: "RemoveExpiredFreeCreditsJob"
  queue: default
